#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in2,    ColorSwitch,    sensorPotentiometer)
#pragma config(Sensor, in3,    AutonSwitch,    sensorPotentiometer)
#pragma config(Sensor, in4,    PowerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  RightShooter,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  TopLimit,       sensorTouch)
#pragma config(Sensor, dgtl4,  BottomLimit,    sensorTouch)
#pragma config(Sensor, dgtl8,  MiddleLimit,    sensorTouch)
#pragma config(Sensor, dgtl9,  LeftShooter,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftDriveEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           BackRightDrive, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FrontRightDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Intake,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Conveyor,      tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           ShooterRight,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ShooterMidRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ShooterLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ShooterMidLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftBackDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          LeftFrontDrive, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define DRIVE(value) motor[port1] = motor[port2] = motor[port9] = motor[port10] = (value)
#define LENC SensorValue[dgtl11]
#define ENC_CPI 135.96 //113.3 - old number
#include "MotionProfileGen.h"
#include "PID_FF.h"
#include "MotionProfileGen.c"
#include "PID_FF.c"

float setpoint = 20; //in inches

task main()
{
	LENC = dist_tra = 0;
	while(1)
	{
		mp_gen(12, 22, setpoint);
		dist_tra = (LENC/ENC_CPI);
		kv = 5.5217;
		kp = 40;
		pid_ff();
		DRIVE(output);
		wait1Msec(25);
	}
}
