#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in2,    ColorSwitch,    sensorPotentiometer)
#pragma config(Sensor, in3,    AutonSwitch,    sensorPotentiometer)
#pragma config(Sensor, in4,    PowerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  RightShooter,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  TopLimit,       sensorTouch)
#pragma config(Sensor, dgtl4,  BottomLimit,    sensorTouch)
#pragma config(Sensor, dgtl5,  DT_Brakes,      sensorDigitalOut)
#pragma config(Sensor, dgtl6,  ShotDeflect,    sensorDigitalOut)
#pragma config(Sensor, dgtl8,  MiddleLimit,    sensorTouch)
#pragma config(Sensor, dgtl9,  LeftShooter,    sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftDriveEncoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           ConveyorMotors, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FrontRightDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftFrontDrive, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           BackRightDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ShooterRight,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ShooterMidRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ShooterLeft,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ShooterMidLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LeftBackDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Intake,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

int a = 0;

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "James_library.h"
#include "SensorSetup.h"
#include "InputProcessing.h"
#include "arcade_drive.h"
#include "Shooter.h"
#include "Intake.h"
#include "Brakes.h"
#include "Output.h"
#include "MotionProfileGen.h"
#include "VelocityProfileGen.h"
#include "PID_FF.h"
#include "Vel_PID_FF.h"
#include "DriveStraight.h"
#include "Turn.h"
#include "Auton.h"
#include "James_library.c"
#include "InputProcessing.c"
#include "arcade_drive.c"
#include "Shooter.c"
#include "Intake.c"
#include "Brakes.c"
#include "Output.c"
#include "MotionProfileGen.c"
#include "VelocityProfileGen.c"
#include "PID_FF.c"
#include "Vel_PID_FF.c"
#include "DriveStraight.c"
#include "Turn.c"
#include "Fourballauto.c"
#include "Fourballautoplus.c"
#include "Fourballautodisrupt.c"
#include "Auton.c"

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	in_auton = false;

	SensorType[in1] = sensorNone; //Gyro Initialization
	wait1Msec(1000);
	SensorType[in1] = sensorGyro;
	wait1Msec(2000);

  dt_init();//init drivetrain
	intake_init();//init intake system
	shooter_init();//init shooter
	pick_auton();
	pick_color();

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	in_auton = true;
	auton_init();
	while(1)
	{
		//process data
  	input_proc();
  	calc_auto_time_left();
  	//auton
		auton_exec();
  	//Control
		brake_decision();
		choice_to_speed();
		collect_value = collect_power[collect_curr_state];
		conveyor_state_machine(vexRT[Btn6D]);//hold 6D to control conveyor with collector
		//Write Motors
		Output();
		wait1Msec(25);
	}
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
//////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	dt_init();//init drivetrain
	intake_init();//init intake system
	shooter_init();//init shooter
	in_auton = false;
	while (true)
	{
		//process data
		input_proc();
		//HMI
		CII(vexRT[Ch3], vexRT[Ch1],vexRT[Btn6U]);//ch3 is wheel, ch1 is throttle,6u is for brakes
		collector(vexRT[Btn5U], vexRT[Btn5D]);//suck - blow
		shot_choice(vexRT[Btn8U], vexRT[Btn8R], vexRT[Btn8D],vexRT[Btn8L]);//choose shooting power
		//Control
		brake_decision();
		choice_to_speed();
		conveyor_state_machine(vexRT[Btn6D]);//hold 6D to control conveyor with collector
		//Write Motors
		Output();
		wait1Msec(25);
	}
}
